# Dropwizard magic so the REST API port can be configured
server:
  applicationConnectors:
    - type: http
      port: 9001 # REST API port
  adminConnectors:
    - type: http
      port: 9081 # Admin UI port